server:
  port: 6666

spring:
  application:
     name: springcloud-gateway
  cloud:
     gateway:
       discovery:
         locator:
           enabled: true # 开启从服务中心动态创建路由的功能
       routes:
         - id: springcloud-foresee1
           uri: lb://springcloud-foresee
           predicates:
             - Path=/companyInfo/**
             - Method=GET

         - id: springcloud-foresee2
           uri: lb://springcloud-foresee
           predicates:
             - Path=/allInfo/**
             - Method=GET

         - id: springcloud-foresee3
           uri: lb://springcloud-foresee
           predicates:
             - Path=/industryInfo/**
             - Method=GET

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    instance-id: springcloud-gateway-6666
    prefer-ip-address: true

