spring:
  profiles:
    active: prod  # 指定配置文件
  application:
     name: spring-cloud-foresee

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://222.200.184.74:8888/eureka/
#      defaultZone: http://localhost:8888/eureka/
  instance:
    instance-id: springcloud-foresee
    prefer-ip-address: true

info:
  app.name: springcloud-foresee
  company.name: www.foresee.com

